"""One `unit` block plus its properties -> one `emet_<unit>` Verilog module.

Follows spec/emet.md's "The compiled monitor" and "The six patterns" sections
literally: three shared declarations, then one `always` block pair (dual
EMET_SIM/formal form) per check, generated by `emit_assert` / `emit_cover`.
"""

from dataclasses import dataclass, field

from . import ast
from .errors import EmetError
from .expr import ExprCompiler, Result, Sym, bits_for

TRIGGERED = (ast.PAt, ast.PWithin, ast.PHold, ast.PStable)


def label_of(name: str) -> str:
    return name.replace("-", "_").replace(".", "_")


def decl_range(width: int) -> str:
    return "" if width == 1 else f"[{width - 1}:0] "


@dataclass
class Check:
    label: str
    window: str
    cond: str
    kind: str  # "assert" or "cover"


@dataclass
class CompiledUnit:
    module_name: str
    verilog: str
    req_ids: list          # requirement IDs with at least one property
    properties: dict        # req_id -> [property label, ...]


class UnitCompiler:
    def __init__(self, path, unit: ast.Unit, properties: list):
        self.path = path
        self.unit = unit
        self.properties = properties
        self.clock = unit.clock
        self.checks: list[Check] = []
        self.decl_lines: list[str] = []      # wires/regs, one block per property
        self.always_lines: list[str] = []      # firing-state always blocks
        self.range_counter = 0

    def error(self, line, msg):
        raise EmetError(self.path, line, msg)

    # ---- driver -----------------------------------------------------------

    def compile(self) -> CompiledUnit:
        unit_scope = self._compile_unit_block()
        matrix: dict[str, list[str]] = {}
        for prop in self.properties:
            if prop.section_id != prop.req_id:
                self.error(
                    prop.line,
                    f"property '{prop.name}' sits under section "
                    f"'{prop.section_id}', not '{prop.req_id}'",
                )
            label = label_of(prop.name)
            matrix.setdefault(prop.req_id, []).append(label)
            self._compile_property(prop, label, dict(unit_scope))
        text = self._assemble()
        return CompiledUnit(f"emet_{self.unit.name.lower()}", text, sorted(matrix), matrix)

    # ---- unit block ---------------------------------------------------------

    def _compile_unit_block(self):
        scope: dict[str, Sym] = {}
        seen = {self.unit.clock}
        for p in self.unit.ports:
            if p.name in scope or p.name == self.unit.clock:
                self.error(p.line, f"duplicate name '{p.name}' in unit block")
            scope[p.name] = Sym("port", p.width, (1 << p.width) - 1, p.name)
            seen.add(p.name)
        reset_text = "1'b0"
        ec = ExprCompiler(self.path, scope)
        for item in self._unit_decl_order():
            if isinstance(item, ast.LetDecl):
                if item.name in scope:
                    self.error(item.line, f"duplicate name '{item.name}' in unit block")
                r = ec.compile(item.expr)
                self._emit_subs(r.subs, "1'b1", f"unit_{item.name}")
                vname = f"emet_let_{item.name}"
                self.decl_lines.append(f"  wire {decl_range(r.width)}{vname} = {r.text};")
                scope[item.name] = Sym("let", r.width, r.max_value, vname)
            elif item is self.unit.reset:
                r = ec.compile(item)
                ExprCompiler(self.path, scope).require_bit(r, self.unit.line, "the reset expression")
                self._emit_subs(r.subs, "1'b1", "unit_reset")
                reset_text = r.text
        self.reset_text = reset_text
        return scope

    def _unit_decl_order(self):
        # The parser doesn't preserve interleaving order of reset vs lets
        # beyond the lists it kept; reset (if any) is semantically independent
        # of let ordering here since the real spec's reset is always a bare
        # port ('clear'). Evaluate lets in source order, then the reset.
        order = list(self.unit.lets)
        if self.unit.reset is not None:
            order.append(self.unit.reset)
        return order

    # ---- properties -----------------------------------------------------------

    def _compile_property(self, prop: ast.Property, label: str, scope: dict):
        triggered = isinstance(prop.pattern, TRIGGERED)
        # spec/emet.md, "Arithmetic does not wrap": every subtraction's __range
        # check is "live in the same window as the property's own check" --
        # one window for the whole property, computable from the pattern type
        # alone, before anything in it is compiled.
        check_window = self._check_window(label, prop.pattern)
        samples = []
        ec = ExprCompiler(self.path, scope)
        for decl in prop.decls:
            if isinstance(decl, ast.SampleDecl) and not triggered:
                self.error(decl.line, "'sample' needs a pattern with a trigger (at/within/hold/stable)")
            r = ec.compile(decl.expr)
            self._emit_subs(r.subs, check_window, f"{label}_{decl.name}")
            if isinstance(decl, ast.LetDecl):
                vname = f"{label}_let_{decl.name}"
                self.decl_lines.append(f"  wire {decl_range(r.width)}{vname} = {r.text};")
                scope[decl.name] = Sym("let", r.width, r.max_value, vname)
            else:
                vname = f"{label}_s_{decl.name}"
                self.decl_lines.append(f"  reg {decl_range(r.width)}{vname};")
                samples.append((decl.name, vname, r))
                scope[decl.name] = Sym("sample", r.width, r.max_value, vname)

        pattern = prop.pattern
        cover_scope = scope
        if pattern is None:
            pass
        elif isinstance(pattern, ast.PInvariant):
            self._compile_invariant(pattern, label, scope, check_window)
        elif isinstance(pattern, (ast.PAt, ast.PWithin, ast.PHold)):
            cover_scope = self._compile_counted(pattern, label, scope, samples, check_window)
        elif isinstance(pattern, ast.PStable):
            self._compile_stable(pattern, label, scope, samples, check_window)
        elif isinstance(pattern, (ast.POnehot, ast.PMutex)):
            self._compile_onehot_mutex(pattern, label, scope, check_window)
        else:
            self.error(prop.line, f"internal: unknown pattern {type(pattern)}")

        cover_window = self._cover_window(label, pattern)
        ec = ExprCompiler(self.path, cover_scope)
        for cov in prop.covers:
            r = ec.compile(cov.expr)
            ec.require_bit(r, cov.line, f"cover '{cov.tag}'")
            self._emit_subs(r.subs, check_window, f"{label}_cover_{cov.tag}")
            self.checks.append(Check(f"{label}_cover_{cov.tag}", cover_window, r.text, "cover"))

    def _cover_window(self, label, pattern):
        if isinstance(pattern, TRIGGERED):
            return f"{label}_busy"
        return "emet_started"

    def _check_window(self, label, pattern):
        """The property's own check window -- spec/emet.md's per-pattern 'W'
        -- computable from the pattern type alone (see each _compile_* method
        for where this same string is used for the check itself)."""
        if isinstance(pattern, ast.PHold) or isinstance(pattern, ast.PStable):
            return f"{label}_live"
        if isinstance(pattern, (ast.PAt, ast.PWithin)):
            return f"{label}_live && {label}_t == {label}_n"
        return "emet_started"

    def _emit_subs(self, subs, window, label_hint):
        for line, cond in subs:
            self.range_counter += 1
            lbl = f"emet_range_{self.range_counter}_{label_hint}"
            self.checks.append(Check(f"{lbl}__range", window, cond, "assert"))

    # ---- invariant -----------------------------------------------------------

    def _compile_invariant(self, pattern: ast.PInvariant, label, scope, check_window):
        ec = ExprCompiler(self.path, scope)
        r = ec.compile(pattern.cond)
        ec.require_bit(r, pattern.line, "an invariant")
        self._emit_subs(r.subs, check_window, label)
        self.checks.append(Check(label, check_window, r.text, "assert"))
        if isinstance(pattern.cond, ast.EBinop) and pattern.cond.op == "->":
            a = ExprCompiler(self.path, scope).compile(pattern.cond.left)
            self.checks.append(Check(f"{label}__fired", "emet_started", a.text, "cover"))

    # ---- at / within / hold -----------------------------------------------------------

    def _compile_counted(self, pattern, label, scope, samples, check_window):
        ec = ExprCompiler(self.path, scope)
        trig = ec.compile(pattern.trigger)
        ec.require_bit(trig, pattern.line, "a trigger")
        self._emit_subs(trig.subs, check_window, f"{label}_trigger")

        # spec/emet.md, "Counts are at least 1": the count is evaluated at the
        # firing edge, the same edge a sample is latched at, so a sample name
        # here means its live defining expression, not the (not-yet-updated)
        # register that will hold last firing's value until this edge retires.
        live_scope = dict(scope)
        for name, vname, r in samples:
            live_scope[name] = Sym("sample", r.width, r.max_value, r.text)
        live_ec = ExprCompiler(self.path, live_scope)
        count = live_ec.compile(pattern.count)
        self._emit_subs(count.subs, check_window, f"{label}_count")
        wn = count.width

        pattern_scope = dict(scope)
        pattern_scope["$t"] = Sym("dollar", wn, count.max_value, f"{label}_t")
        pattern_scope["$n"] = Sym("dollar", wn, count.max_value, f"{label}_n")
        cond_ec = ExprCompiler(self.path, pattern_scope)
        cond = cond_ec.compile(pattern.cond)
        cond_ec.require_bit(cond, pattern.line, "the checked condition")

        is_within = isinstance(pattern, ast.PWithin)
        L = label
        self.decl_lines.append(f"  reg [{wn - 1}:0] {L}_t = 0, {L}_n = 0;")
        self.decl_lines.append(f"  reg {L}_busy = 1'b0;")
        self.decl_lines.append(f"  wire {L}_live = {L}_busy && !emet_reset;")
        retire_extra = ""
        if is_within:
            self.decl_lines.append(f"  wire {L}_hit = {L}_live && ({cond.text});")
            retire_extra = f" || {L}_hit"
        self.decl_lines.append(
            f"  wire {L}_retire = {L}_busy && (emet_reset || {L}_t == {L}_n{retire_extra});"
        )
        self.decl_lines.append(f"  wire {L}_fire = emet_started && ({trig.text});")

        body = [f"  always @(posedge {self.clock}) begin"]
        body.append(f"    if ({L}_retire) {L}_busy <= 1'b0;")
        body.append(f"    else if ({L}_busy) {L}_t <= {L}_t + 1'b1;")
        body.append(f"    if ({L}_fire) begin")
        body.append(f"      {L}_busy <= 1'b1;")
        body.append(f"      {L}_t <= 1;")
        body.append(f"      {L}_n <= ({count.text});")
        for name, vname, r in samples:
            body.append(f"      {vname} <= ({r.text});")
        body.append(f"    end")
        body.append(f"  end")
        self.always_lines.extend(body)

        self.checks.append(Check(f"{L}__overlap", "1'b1",
                                  f"!({L}_fire && {L}_busy && !{L}_retire)", "assert"))
        self.checks.append(Check(f"{L}__range", "1'b1",
                                  f"!{L}_fire || (({count.text}) >= 1)", "assert"))

        self._emit_subs(cond.subs, check_window, label)
        self.checks.append(Check(L, check_window, cond.text, "assert"))
        if is_within:
            self.checks.append(Check(f"{L}__fired", "1'b1", f"{L}_hit", "cover"))
        else:
            self.checks.append(Check(f"{L}__fired", "1'b1", f"{L}_live && {L}_t == {L}_n", "cover"))
        return pattern_scope

    # ---- stable -----------------------------------------------------------

    def _compile_stable(self, pattern: ast.PStable, label, scope, samples, check_window):
        ec = ExprCompiler(self.path, scope)
        trig = ec.compile(pattern.trigger)
        ec.require_bit(trig, pattern.line, "a trigger")
        self._emit_subs(trig.subs, check_window, f"{label}_trigger")

        value = ec.compile(pattern.expr)
        self._emit_subs(value.subs, check_window, f"{label}_value")

        release = ec.compile(pattern.release)
        ec.require_bit(release, pattern.line, "a release condition")

        L = label
        wv = value.width
        self.decl_lines.append(f"  reg {L}_busy = 1'b0;")
        self.decl_lines.append(f"  reg [{wv - 1}:0] {L}_v;")
        self.decl_lines.append(f"  wire {L}_live = {L}_busy && !emet_reset;")
        self.decl_lines.append(f"  wire {L}_retire = {L}_busy && (emet_reset || ({release.text}));")

        body = [f"  always @(posedge {self.clock}) begin"]
        body.append(f"    if ({L}_retire) {L}_busy <= 1'b0;")
        body.append(f"    if (emet_started && ({trig.text})) begin")
        body.append(f"      {L}_busy <= 1'b1;")
        body.append(f"      {L}_v <= ({value.text});")
        for name, vname, r in samples:
            body.append(f"      {vname} <= ({r.text});")
        body.append(f"    end")
        body.append(f"  end")
        self.always_lines.extend(body)
        self._emit_subs(release.subs, check_window, f"{label}_release")

        self.checks.append(Check(L, check_window, f"({value.text}) == {L}_v", "assert"))
        self.checks.append(Check(f"{L}__fired", "1'b1", f"{L}_live && ({release.text})", "cover"))

    # ---- onehot / mutex -----------------------------------------------------------

    def _compile_onehot_mutex(self, pattern, label, scope, check_window):
        ec = ExprCompiler(self.path, scope)
        results = []
        for c in pattern.conds:
            r = ec.compile(c)
            ec.require_bit(r, pattern.line, "each onehot/mutex entry")
            self._emit_subs(r.subs, check_window, label)
            results.append(r)
        k = len(results)
        bits_text = "{" + ", ".join(r.text for r in reversed(results)) + "}"
        L = label
        self.decl_lines.append(f"  wire [{k - 1}:0] {L}_bits = {bits_text};")
        if isinstance(pattern, ast.POnehot):
            cond = f"{L}_bits != 0 && ({L}_bits & ({L}_bits - 1)) == 0"
        else:
            cond = f"({L}_bits & ({L}_bits - 1)) == 0"
        self.checks.append(Check(L, check_window, cond, "assert"))

    # ---- assembly -----------------------------------------------------------

    def _assemble(self) -> str:
        u = self.unit
        module = f"emet_{u.name.lower()}"
        ports = [f"    input  wire        {u.clock},"]
        for p in u.ports:
            wtxt = "       " if p.width == 1 else f"[{p.width - 1}:0]"
            ports.append(f"    input  wire {wtxt.ljust(11)} {p.name},")
        ports.append("    output wire        emet_fail")

        lines = []
        lines.append(f"// Generated by the emet compiler from {self.path}. Do not edit.")
        lines.append("`default_nettype none")
        lines.append(f"module {module} (")
        lines.append("\n".join(ports))
        lines.append(");")
        lines.append(f"  reg emet_started = 1'b0;")
        lines.append(f"  always @(posedge {u.clock}) emet_started <= 1'b1;")
        lines.append(f"  wire emet_reset = {self.reset_text};")
        lines.append("`ifdef EMET_SIM")
        lines.append("  reg [31:0] emet_edge = 32'd0;")
        lines.append(f"  always @(posedge {u.clock}) emet_edge <= emet_edge + 32'd1;")
        lines.append("`endif")
        lines.append("")
        lines.extend(self.decl_lines)
        lines.append("")
        lines.extend(self.always_lines)
        lines.append("")
        fail_terms = []
        for chk in self.checks:
            lines.append("")
            if chk.kind == "assert":
                lines.append(self._emit_assert(chk))
                fail_terms.append(f"{chk.label}_fail")
            else:
                lines.append(self._emit_cover(chk))
        lines.append("")
        lines.append("`ifdef EMET_SIM")
        if fail_terms:
            lines.append(f"  assign emet_fail = {' || '.join(fail_terms)};")
        else:
            lines.append("  assign emet_fail = 1'b0;")
        lines.append("`else")
        lines.append("  assign emet_fail = 1'b0;")
        lines.append("`endif")
        lines.append("endmodule")
        return "\n".join(lines) + "\n"

    def _emit_assert(self, chk: Check) -> str:
        L = chk.label
        return (
            "`ifdef EMET_SIM\n"
            f"  reg {L}_fail = 1'b0;\n"
            f"  always @(posedge {self.clock})\n"
            f"    if ({chk.window}) if (({chk.cond}) !== 1'b1) begin\n"
            f'      $display("emet: {L} failed at edge %0d (%0t)", emet_edge, $time);\n'
            f"      {L}_fail <= 1'b1;\n"
            "    end\n"
            "`else\n"
            f"  always @(posedge {self.clock}) if ({chk.window}) {L}: assert ({chk.cond});\n"
            "`endif"
        )

    def _emit_cover(self, chk: Check) -> str:
        L = chk.label
        return (
            "`ifdef EMET_SIM\n"
            f"  reg {L}_hit = 1'b0;\n"
            f"  always @(posedge {self.clock}) if ({chk.window}) if (({chk.cond}) === 1'b1) {L}_hit <= 1'b1;\n"
            "`else\n"
            f"  always @(posedge {self.clock}) if ({chk.window}) {L}: cover ({chk.cond});\n"
            "`endif"
        )
