"""Everything written under formal/emet/generated/: the monitor Verilog (from
compile_unit), a formal harness + .sby job per unit, the sim-side hierarchical
wiring `` `include``d by test/tb.v, a Makefile fragment listing the monitor
sources for cocotb, and the traceability matrix.

Design decisions (issue #19):

1. Reaching a unit that is not the top module (sim): `test/tb.v` reaches a
   block's ports through a hierarchical reference `user_project.<module>.<port>`,
   relying on the convention--true today, see rtl/--that a Hardcaml-generated
   top level instantiates a block using the block's own module name as the
   instance name. If a future block breaks that convention, `make sim` fails
   loudly (unknown hierarchical name) and the fix is a one-line instance
   rename in rtl/, not a change to this file.
2. Formal does not have this problem: it never goes through the pin-mapped
   top, it instantiates the block module directly (see `_formal_harness`
   below), exactly like the hand-written `formal/uart_tx.sby` it replaces the
   pattern of.
"""

from pathlib import Path

from . import ast
from .compile_unit import CompiledUnit
from .expr import ExprCompiler, Sym


def write_monitor(generated: Path, compiled: CompiledUnit) -> Path:
    path = generated / f"{compiled.module_name}.v"
    path.write_text(compiled.verilog)
    return path


def formal_harness(unit: ast.Unit, compiled: CompiledUnit) -> str:
    module = f"{compiled.module_name}_formal"
    ins = [p for p in unit.ports if p.direction == "in"]
    outs = [p for p in unit.ports if p.direction == "out"]
    lines = [
        f"// Generated by the emet compiler: formal harness for {unit.module}.",
        "// Instantiates the DUT and the emet monitor on the same nets. Do not edit.",
        "`default_nettype none",
        f"module {module} (",
        "    input wire " + unit.clock + ",",
    ]
    for p in ins:
        w = "" if p.width == 1 else f"[{p.width - 1}:0] "
        lines.append(f"    input wire {w}{p.name},")
    lines[-1] = lines[-1].rstrip(",")
    lines.append(");")
    if outs:
        decl = ", ".join(p.name for p in outs)
        lines.append(f"  wire {decl};")
    conn_list = [f".{unit.clock}({unit.clock})"] + [f".{p.name}({p.name})" for p in unit.ports]
    lines.append(f"  {unit.module} dut (")
    lines.append("      " + ",\n      ".join(conn_list))
    lines.append("  );")
    lines.append(f"  {compiled.module_name} monitor (")
    mon_conns = [f".{unit.clock}({unit.clock})"] + [f".{p.name}({p.name})" for p in unit.ports] + [".emet_fail()"]
    lines.append("      " + ",\n      ".join(mon_conns))
    lines.append("  );")
    if unit.reset is not None:
        # spec/emet.md's execution model starts every trace at edge 1 with
        # nothing yet clocked; the monitor itself handles that (`emet_started`).
        # The *design* has no such guarantee here -- unlike a real reset button,
        # PDR is free to start it in any state -- so the harness (not the
        # monitor: `emet.md` bans `assume` from emet itself) constrains the
        # first sampled edge to be a reset edge, the same role
        # `formal/uart_tx_props.v`'s `past_valid`/`assume` pair plays by hand.
        port_scope = {unit.clock: Sym("port", 1, 1, unit.clock)}
        port_scope.update({p.name: Sym("port", p.width, (1 << p.width) - 1, p.name) for p in unit.ports})
        # Already validated once by UnitCompiler; re-compiled here only to get
        # Verilog text against the harness's own (identically named) ports.
        reset_text = ExprCompiler("<formal harness>", port_scope).compile(unit.reset).text
        lines.append("  reg emet_formal_past_valid = 1'b0;")
        lines.append(f"  always @(posedge {unit.clock}) emet_formal_past_valid <= 1'b1;")
        lines.append(f"  always @(*) if (!emet_formal_past_valid) assume ({reset_text});")
    lines.append("endmodule")
    return "\n".join(lines) + "\n"


def sby_job(unit: ast.Unit, compiled: CompiledUnit, spec_rel: Path) -> str:
    module = compiled.module_name
    formal_module = f"{module}_formal"
    return f"""\
# Generated by the emet compiler from {spec_rel}. Do not edit.
#   prove: unbounded proof of every emet-compiled assertion (PDR, no depth limit)
#   cover: every cover directive (incl. the compiler's own __fired) is reachable
[tasks]
prove
cover

[options]
prove: mode prove
cover: mode cover
cover: depth 40

[engines]
prove: abc pdr
cover: smtbmc boolector

[script]
read -formal golem.v
read -formal {module}.v
read -formal {formal_module}.v
prep -top {formal_module}

[files]
../../../src/golem.v
{module}.v
{formal_module}.v
"""


def tb_include(results, top_instance="user_project") -> str:
    lines = ["// Generated by the emet compiler. `` `include``d by test/tb.v. Do not edit."]
    fail_terms = []
    for r in results:
        if r.compiled is None:
            continue
        unit, compiled = r.unit, r.compiled
        inst = f"{compiled.module_name}_inst"
        fail = f"{compiled.module_name}_fail"
        conns = [f".{unit.clock}({top_instance}.{unit.module}.{unit.clock})"]
        conns += [f".{p.name}({top_instance}.{unit.module}.{p.name})" for p in unit.ports]
        conns.append(f".emet_fail({fail})")
        lines.append(f"wire {fail};")
        lines.append(f"{compiled.module_name} {inst} (")
        lines.append("    " + ",\n    ".join(conns))
        lines.append(");")
        fail_terms.append(fail)
    fail_expr = " | ".join(fail_terms) if fail_terms else "1'b0"
    lines.append(f"wire emet_any_fail = {fail_expr};")
    return "\n".join(lines) + "\n"


def sim_sources_mk(results) -> str:
    paths = [f"../formal/emet/generated/{r.compiled.module_name}.v" for r in results if r.compiled]
    return "EMET_GENERATED_SOURCES = " + " ".join(paths) + "\n"


def covers_py(results) -> str:
    lines = ["# Generated by the emet compiler. Do not edit.", "COVERS = ["]
    for r in results:
        if r.compiled is None:
            continue
        inst = f"{r.compiled.module_name}_inst"
        for chk in _cover_labels(r):
            lines.append(f'    ("{inst}", "{chk}"),')
    lines.append("]")
    return "\n".join(lines) + "\n"


def _cover_labels(result):
    # The compiled Verilog carries every cover/`__fired` label as `<label>_hit`
    # under `` `ifdef EMET_SIM``; scrape them back out rather than plumbing a
    # second copy of the check list through compile_unit's return value.
    import re
    return re.findall(r"reg\s+(\w+)_hit\s*=\s*1'b0;", result.compiled.verilog)


def traceability_md(results) -> str:
    lines = [
        "<!-- Generated by the emet compiler. Do not edit. -->",
        "# emet traceability matrix",
        "",
        "Requirement ID -> the emet properties that check it. Mutation-kill status is not",
        "yet wired up for emet monitors (issue #19, point 5): `mcy` runs against `formal/*.sby`",
        "today and generated jobs are picked up the same way, but per-property kill rates are",
        "future work, tracked in the PR.",
        "",
        "| Requirement | Unit | Properties |",
        "|---|---|---|",
    ]
    for r in results:
        if r.compiled is None:
            continue
        for req_id in r.compiled.req_ids:
            props = ", ".join(f"`{p}`" for p in r.compiled.properties[req_id])
            lines.append(f"| {req_id} | {r.unit.name} | {props} |")
    return "\n".join(lines) + "\n"
