// GENERATED by rtl/bin/generate.ml from the Hardcaml sources in rtl/src. Do not edit:
// change the OCaml and run `make rtl`.
module golem_uart_tx (
    data,
    divisor,
    clear,
    clock,
    valid,
    tx,
    ready
);

    input [7:0] data;
    input [15:0] divisor;
    input clear;
    input clock;
    input valid;
    output tx;
    output ready;

    wire _23;
    wire _69;
    wire [7:0] _25;
    wire [6:0] _41;
    wire [7:0] _42;
    wire [7:0] _43;
    wire [7:0] _44;
    wire [7:0] _3;
    wire [7:0] _27;
    wire [7:0] _45;
    wire [7:0] _4;
    reg [7:0] shift;
    wire _75;
    wire [3:0] _73;
    wire _74;
    wire _76;
    wire _77;
    wire _79;
    wire _80;
    wire _71;
    wire _72;
    wire [3:0] _38;
    wire [3:0] _36;
    wire [3:0] _48;
    wire [3:0] _49;
    wire [3:0] _50;
    wire [3:0] _51;
    wire [3:0] _47;
    wire [3:0] _52;
    wire [3:0] _5;
    reg [3:0] bit_index;
    wire _39;
    wire _65;
    wire [15:0] _32;
    wire [15:0] _7;
    wire [15:0] _53;
    wire [15:0] _54;
    wire [15:0] _8;
    reg [15:0] period;
    wire vdd;
    wire _10;
    wire _12;
    wire [15:0] _57;
    wire [15:0] _58;
    wire [15:0] _60;
    wire [15:0] _56;
    wire [15:0] _61;
    wire [15:0] _13;
    reg [15:0] cycle;
    wire end_of_bit;
    wire _66;
    wire _15;
    wire _63;
    wire _67;
    wire _16;
    reg busy;
    wire _81;
    wire _17;
    reg tx_n;
    wire _82;
    assign _23 = ~ busy;
    assign _69 = 1'b0;
    assign _25 = 8'b00000000;
    assign _41 = shift[7:1];
    assign _42 = { _69,
                   _41 };
    assign _43 = _39 ? shift : _42;
    assign _44 = end_of_bit ? _43 : shift;
    assign _3 = data;
    assign _27 = _15 ? _3 : shift;
    assign _45 = busy ? _44 : _27;
    assign _4 = _45;
    always @(posedge _12) begin
        if (_10)
            shift <= _25;
        else
            shift <= _4;
    end
    assign _75 = shift[0:0];
    assign _73 = 4'b1000;
    assign _74 = bit_index == _73;
    assign _76 = _74 ? vdd : _75;
    assign _77 = ~ _76;
    assign _79 = _39 ? _69 : _77;
    assign _80 = end_of_bit ? _79 : tx_n;
    assign _71 = 1'b1;
    assign _72 = _15 ? _71 : tx_n;
    assign _38 = 4'b1001;
    assign _36 = 4'b0000;
    assign _48 = 4'b0001;
    assign _49 = bit_index + _48;
    assign _50 = _39 ? bit_index : _49;
    assign _51 = end_of_bit ? _50 : bit_index;
    assign _47 = _15 ? _36 : bit_index;
    assign _52 = busy ? _51 : _47;
    assign _5 = _52;
    always @(posedge _12) begin
        if (_10)
            bit_index <= _36;
        else
            bit_index <= _5;
    end
    assign _39 = bit_index == _38;
    assign _65 = _39 ? _69 : busy;
    assign _32 = 16'b0000000000000000;
    assign _7 = divisor;
    assign _53 = _15 ? _7 : period;
    assign _54 = busy ? period : _53;
    assign _8 = _54;
    always @(posedge _12) begin
        if (_10)
            period <= _32;
        else
            period <= _8;
    end
    assign vdd = 1'b1;
    assign _10 = clear;
    assign _12 = clock;
    assign _57 = 16'b0000000000000001;
    assign _58 = cycle + _57;
    assign _60 = end_of_bit ? _32 : _58;
    assign _56 = _15 ? _32 : cycle;
    assign _61 = busy ? _60 : _56;
    assign _13 = _61;
    always @(posedge _12) begin
        if (_10)
            cycle <= _32;
        else
            cycle <= _13;
    end
    assign end_of_bit = cycle == period;
    assign _66 = end_of_bit ? _65 : busy;
    assign _15 = valid;
    assign _63 = _15 ? _71 : busy;
    assign _67 = busy ? _66 : _63;
    assign _16 = _67;
    always @(posedge _12) begin
        if (_10)
            busy <= _69;
        else
            busy <= _16;
    end
    assign _81 = busy ? _80 : _72;
    assign _17 = _81;
    always @(posedge _12) begin
        if (_10)
            tx_n <= _69;
        else
            tx_n <= _17;
    end
    assign _82 = ~ tx_n;
    assign tx = _82;
    assign ready = _23;

endmodule
/* verilator lint_off UNUSEDSIGNAL */
module tt_um_rechefe_golem (
    uio_in,
    ui_in,
    rst_n,
    clk,
    ena,
    uo_out,
    uio_out,
    uio_oe
);

    input [7:0] uio_in;
    input [7:0] ui_in;
    input rst_n;
    input clk;
    input ena;
    output [7:0] uo_out;
    output [7:0] uio_out;
    output [7:0] uio_oe;

    wire [7:0] _12;
    wire _21;
    wire [15:0] _17;
    wire [7:0] _4;
    wire _16;
    wire [7:0] _6;
    wire _8;
    wire _15;
    wire _10;
    wire [1:0] _19;
    wire _20;
    wire [1:0] _22;
    wire [5:0] _14;
    wire [7:0] _23;
    assign _12 = 8'b00000000;
    assign _21 = _19[0:0];
    assign _17 = 16'b0000000110100001;
    assign _4 = uio_in;
    assign _16 = _4[0:0];
    assign _6 = ui_in;
    assign _8 = rst_n;
    assign _15 = ~ _8;
    assign _10 = clk;
    golem_uart_tx
        golem_uart_tx
        ( .clock(_10),
          .clear(_15),
          .data(_6),
          .valid(_16),
          .divisor(_17),
          .ready(_19[1:1]),
          .tx(_19[0:0]) );
    assign _20 = _19[1:1];
    assign _22 = { _20,
                   _21 };
    assign _14 = 6'b000000;
    assign _23 = { _14,
                   _22 };
    assign uo_out = _23;
    assign uio_out = _12;
    assign uio_oe = _12;

endmodule
/* verilator lint_on UNUSEDSIGNAL */
